/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as DashboardRecordsRouteImport } from './routes/dashboard/records'
import { Route as DashboardProfileRouteImport } from './routes/dashboard/profile'
import { Route as DashboardChatRouteImport } from './routes/dashboard/chat'
import { Route as DashboardAppointmentsRouteImport } from './routes/dashboard/appointments'
import { Route as Dashboard_layoutRouteImport } from './routes/dashboard/__layout'
import { Route as AuthForgotPasswordRouteImport } from './routes/auth/forgot-password'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminPatientsRouteImport } from './routes/admin/patients'
import { Route as AdminDoctorsRouteImport } from './routes/admin/doctors'
import { Route as AdminAppointmentsRouteImport } from './routes/admin/appointments'
import { Route as Admin_layoutRouteImport } from './routes/admin/__layout'
import { Route as AuthRegisterIndexRouteImport } from './routes/auth/register/index'
import { Route as AuthLoginIndexRouteImport } from './routes/auth/login/index'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRecordsRoute = DashboardRecordsRouteImport.update({
  id: '/dashboard/records',
  path: '/dashboard/records',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/dashboard/profile',
  path: '/dashboard/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardChatRoute = DashboardChatRouteImport.update({
  id: '/dashboard/chat',
  path: '/dashboard/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAppointmentsRoute = DashboardAppointmentsRouteImport.update({
  id: '/dashboard/appointments',
  path: '/dashboard/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const Dashboard_layoutRoute = Dashboard_layoutRouteImport.update({
  id: '/dashboard/__layout',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotPasswordRoute = AuthForgotPasswordRouteImport.update({
  id: '/auth/forgot-password',
  path: '/auth/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPatientsRoute = AdminPatientsRouteImport.update({
  id: '/admin/patients',
  path: '/admin/patients',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDoctorsRoute = AdminDoctorsRouteImport.update({
  id: '/admin/doctors',
  path: '/admin/doctors',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAppointmentsRoute = AdminAppointmentsRouteImport.update({
  id: '/admin/appointments',
  path: '/admin/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const Admin_layoutRoute = Admin_layoutRouteImport.update({
  id: '/admin/__layout',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterIndexRoute = AuthRegisterIndexRouteImport.update({
  id: '/auth/register/',
  path: '/auth/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/auth/login/',
  path: '/auth/login/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof Admin_layoutRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/doctors': typeof AdminDoctorsRoute
  '/admin/patients': typeof AdminPatientsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/dashboard': typeof Dashboard_layoutRoute
  '/dashboard/appointments': typeof DashboardAppointmentsRoute
  '/dashboard/chat': typeof DashboardChatRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/records': typeof DashboardRecordsRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/auth/login/': typeof AuthLoginIndexRoute
  '/auth/register/': typeof AuthRegisterIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminIndexRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/doctors': typeof AdminDoctorsRoute
  '/admin/patients': typeof AdminPatientsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/appointments': typeof DashboardAppointmentsRoute
  '/dashboard/chat': typeof DashboardChatRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/records': typeof DashboardRecordsRoute
  '/auth/login': typeof AuthLoginIndexRoute
  '/auth/register': typeof AuthRegisterIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin/__layout': typeof Admin_layoutRoute
  '/admin/appointments': typeof AdminAppointmentsRoute
  '/admin/doctors': typeof AdminDoctorsRoute
  '/admin/patients': typeof AdminPatientsRoute
  '/admin/users': typeof AdminUsersRoute
  '/auth/forgot-password': typeof AuthForgotPasswordRoute
  '/dashboard/__layout': typeof Dashboard_layoutRoute
  '/dashboard/appointments': typeof DashboardAppointmentsRoute
  '/dashboard/chat': typeof DashboardChatRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/records': typeof DashboardRecordsRoute
  '/admin/': typeof AdminIndexRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/auth/login/': typeof AuthLoginIndexRoute
  '/auth/register/': typeof AuthRegisterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/admin/appointments'
    | '/admin/doctors'
    | '/admin/patients'
    | '/admin/users'
    | '/auth/forgot-password'
    | '/dashboard'
    | '/dashboard/appointments'
    | '/dashboard/chat'
    | '/dashboard/profile'
    | '/dashboard/records'
    | '/admin/'
    | '/dashboard/'
    | '/auth/login/'
    | '/auth/register/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/admin/appointments'
    | '/admin/doctors'
    | '/admin/patients'
    | '/admin/users'
    | '/auth/forgot-password'
    | '/dashboard'
    | '/dashboard/appointments'
    | '/dashboard/chat'
    | '/dashboard/profile'
    | '/dashboard/records'
    | '/auth/login'
    | '/auth/register'
  id:
    | '__root__'
    | '/'
    | '/admin/__layout'
    | '/admin/appointments'
    | '/admin/doctors'
    | '/admin/patients'
    | '/admin/users'
    | '/auth/forgot-password'
    | '/dashboard/__layout'
    | '/dashboard/appointments'
    | '/dashboard/chat'
    | '/dashboard/profile'
    | '/dashboard/records'
    | '/admin/'
    | '/dashboard/'
    | '/auth/login/'
    | '/auth/register/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  Admin_layoutRoute: typeof Admin_layoutRoute
  AdminAppointmentsRoute: typeof AdminAppointmentsRoute
  AdminDoctorsRoute: typeof AdminDoctorsRoute
  AdminPatientsRoute: typeof AdminPatientsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AuthForgotPasswordRoute: typeof AuthForgotPasswordRoute
  Dashboard_layoutRoute: typeof Dashboard_layoutRoute
  DashboardAppointmentsRoute: typeof DashboardAppointmentsRoute
  DashboardChatRoute: typeof DashboardChatRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardRecordsRoute: typeof DashboardRecordsRoute
  AdminIndexRoute: typeof AdminIndexRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthRegisterIndexRoute: typeof AuthRegisterIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/records': {
      id: '/dashboard/records'
      path: '/dashboard/records'
      fullPath: '/dashboard/records'
      preLoaderRoute: typeof DashboardRecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/dashboard/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/chat': {
      id: '/dashboard/chat'
      path: '/dashboard/chat'
      fullPath: '/dashboard/chat'
      preLoaderRoute: typeof DashboardChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/appointments': {
      id: '/dashboard/appointments'
      path: '/dashboard/appointments'
      fullPath: '/dashboard/appointments'
      preLoaderRoute: typeof DashboardAppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/__layout': {
      id: '/dashboard/__layout'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof Dashboard_layoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot-password': {
      id: '/auth/forgot-password'
      path: '/auth/forgot-password'
      fullPath: '/auth/forgot-password'
      preLoaderRoute: typeof AuthForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/patients': {
      id: '/admin/patients'
      path: '/admin/patients'
      fullPath: '/admin/patients'
      preLoaderRoute: typeof AdminPatientsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/doctors': {
      id: '/admin/doctors'
      path: '/admin/doctors'
      fullPath: '/admin/doctors'
      preLoaderRoute: typeof AdminDoctorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/appointments': {
      id: '/admin/appointments'
      path: '/admin/appointments'
      fullPath: '/admin/appointments'
      preLoaderRoute: typeof AdminAppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/__layout': {
      id: '/admin/__layout'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof Admin_layoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register/': {
      id: '/auth/register/'
      path: '/auth/register'
      fullPath: '/auth/register/'
      preLoaderRoute: typeof AuthRegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login/': {
      id: '/auth/login/'
      path: '/auth/login'
      fullPath: '/auth/login/'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  Admin_layoutRoute: Admin_layoutRoute,
  AdminAppointmentsRoute: AdminAppointmentsRoute,
  AdminDoctorsRoute: AdminDoctorsRoute,
  AdminPatientsRoute: AdminPatientsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AuthForgotPasswordRoute: AuthForgotPasswordRoute,
  Dashboard_layoutRoute: Dashboard_layoutRoute,
  DashboardAppointmentsRoute: DashboardAppointmentsRoute,
  DashboardChatRoute: DashboardChatRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardRecordsRoute: DashboardRecordsRoute,
  AdminIndexRoute: AdminIndexRoute,
  DashboardIndexRoute: DashboardIndexRoute,
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthRegisterIndexRoute: AuthRegisterIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
